### ISSUE TITLE
Dependencies on doctest >= 0.13

### ISSUE THREAD

**Issue by drever** [Gabriel439/Haskell-Pipes-Group-Library#14]
Hello Gabriel,

I'm trying to build a Haskell project with a dependency on `pipes-group`. Nix picks the most recent version `1.0.9`. This version does in turn have a dependency on `doctest >= 0.9.12 && <0.13`. Nix also picks `doctest-0.13.0` and thus encounters a missing dependency.

I'm still a little new with the nix and Haskell build process, so pardon me if this problem has a trivial solution. Would it be possible to raise the upper bound on the `doctest` dependency?

Regards,
Johannes

**Comment by Gabriel439** [comment]
Oh yeah, I can definitely raise the upper bound.  The only reason that I haven't done so already is that I don't remember getting a Stackage notification for `pipes-group` having a stale upper bound

**Comment by Gabriel439** [comment]
Note that it's not on Hackage, yet.  Apparently I published two releases that I forgot to sync with the `master` branch of this repository.  I need to hunt them down first and merge them back into mainline before I can push this fix to Hackage.

**Comment by drever** [comment]
The diff looks pretty reasonable, though

https://gist.github.com/drever/cf73dc7c85979668068cda96c292ca13

**Comment by Gabriel439** [comment]
Alright, I found the missing history so this is now up on Hackage as `pipes-group-1.0.10`

**Comment by drever** [comment]
How does the new release end up in `nixpkgs`?

**Comment by Gabriel439** [comment]
@drever: There's an automatic update every 3 days.  See: https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/haskell-modules/hackage-packages.nix
