### ISSUE TITLE
Bad Haddock link on Hackage

### ISSUE THREAD

**Issue by FranklinChen** [Gabriel439/Haskell-Pipes-Group-Library#8]
I noticed that the Contents link at http://hackage.haskell.org/package/pipes-group-1.0.3/docs/Pipes-Group.html is somehow `c:/Program%20Files%20(x86)/Git/package/pipes-group`

**Comment by Gabriel439** [comment]
Oh, this is because I had to do a manual Haddocks upload.  I will see if I can upload again to fix this issue

**Comment by Gabriel439** [comment]
Alright, this is fixed now.  Apparently the manual haddocks tool does not work on Windows, but rerunning it from either OS X or Linux works.
